### PR TITLE
Add simple `multiply2` XNNPACK example

### PR DESCRIPTION
**Pull request by ramiro050**
This commit replaces the multiplication of tensors in the system plugin example with a call to XNNPACK's multiply2. The plugin runs e2e correctly.

Note: the CMake changes are very hacky. I just needed to get the ball rolling.

### CODE REVIEW

**Comment by ramiro050** [comment]
Running:

```
../iree-build/tools/iree-run-module \
                              --device=local-sync \
                              --executable_plugin=../iree-build/samples/custom_dispatch/cpu/plugin/system_plugin.so \
                              --function=mixed_invocation \
                              --input=8xf32=2 \
                              --input=8xf32=4 \
                              --module=/tmp/example.vmfb
```

produces:

```
EXEC @mixed_invocation
processor_id=4
processor_data[0]=1F0CC0F
mul2[0:0](2 * 4 = 8)
mul2[0:1](2 * 4 = 8)
mul2[0:2](2 * 4 = 8)
mul2[0:3](2 * 4 = 8)
mul2[0:4](2 * 4 = 8)
mul2[0:5](2 * 4 = 8)
mul2[0:6](2 * 4 = 8)
mul2[0:7](2 * 4 = 8)
result[0]: hal.buffer_view
8xf32=12 12 12 12 12 12 12 12
```

**Comment by okkwon** [comment]
Do you know why the output values are all 12 instead of 8?

**Comment by okkwon** [comment]
It would be nice to create a new folder for the work. Otherwise, it is really a good start!

**Comment by ramiro050** [comment]
> Do you know why the output values are all 12 instead of 8?

Yeah, there is an extra `add` in the example MLIR to show that you can mix external calls with builtin MLIR ops:

https://github.com/ramiro050/iree/blob/981e7ade26f7d47a0db676afcc5f4804d0fa6ded/samples/custom_dispatch/cpu/plugin/system_example.mlir#L134-L138

**Comment by ramiro050** [comment]
> It would be nice to create a new folder for the work. Otherwise, it is really a good start!

Agreed! I'll refactor things in a follow up patch.

**Pull request merged**
