### PR TITLE
Add conversion from XNNPACK dialect to ukernels

### PR DESCRIPTION
**Pull request by ramiro050**

### CODE REVIEW

**Comment by ramiro050** [comment]
Running 

```
iree-compile --iree-hal-target-backends=llvm-cpu --iree-plugin=xnnpack_sample samples/compiler_plugins/xnnpack/test/xnnpack-legalize.mlir --mlir-print-ir-after-all --mlir-print-ir-after-change
```

creates

```mlir
// -----// IR Dump After LegalizeXnnpack (iree-xnnpack-legalize) //----- //
#executable_target_embedded_elf_x86_64_ = #hal.executable.target<"llvm-cpu", "embedded-elf-x86_64", {cpu = "generic", cpu_features = "", data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-unknown-unknown-eabi-elf", ukernels = false}>
#device_target_llvm_cpu = #hal.device.target<"llvm-cpu", {executable_targets = [#executable_target_embedded_elf_x86_64_]}>
module attributes {hal.device.targets = [#device_target_llvm_cpu]} {
  func.func private @xnnpack.mul2(%arg0: tensor<?xf32>, %arg1: tensor<?xf32>) -> tensor<?xf32> {
    %c0 = arith.constant 0 : index
    %dim = tensor.dim %arg0, %c0 : tensor<?xf32>
    %0 = tensor.empty(%dim) : tensor<?xf32>
    %1 = flow.dispatch.region -> (tensor<?xf32>{%dim}) {
      %2 = iree_codegen.ukernel.generic "xnnpack.mul2_workgroup" ins(%arg0, %arg1 : tensor<?xf32>, tensor<?xf32>) outs(%0 : tensor<?xf32>) (%dim : index) -> tensor<?xf32>
      flow.return %2 : tensor<?xf32>
    }
    return %1 : tensor<?xf32>
  }
  func.func @main(%arg0: !hal.buffer_view, %arg1: !hal.buffer_view) -> !hal.buffer_view attributes {iree.abi.stub} {
    %c0 = arith.constant 0 : index
    %0 = hal.buffer_view.dim<%arg0 : !hal.buffer_view>[0] : index
    %1 = hal.tensor.import %arg0 "input 0" : !hal.buffer_view -> tensor<?xf32>{%0}
    %2 = hal.buffer_view.dim<%arg1 : !hal.buffer_view>[0] : index
    %3 = hal.tensor.import %arg1 "input 1" : !hal.buffer_view -> tensor<?xf32>{%2}
    %4 = call @_main(%1, %3) : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32>
    %dim = tensor.dim %4, %c0 : tensor<?xf32>
    %5 = hal.tensor.export %4 "output 0" : tensor<?xf32>{%dim} -> !hal.buffer_view
    return %5 : !hal.buffer_view
  }
  func.func private @_main(%arg0: tensor<?xf32>, %arg1: tensor<?xf32>) -> tensor<?xf32> {
    %0 = call @xnnpack.mul2(%arg0, %arg1) : (tensor<?xf32>, tensor<?xf32>) -> tensor<?xf32>
    return %0 : tensor<?xf32>
  }
}
```

I still need to debug a couple of things, hence "Draft" state.

**Comment by okkwon** [comment]
Can you upload the full dump to gist? I'd like to see how the private function is lowered into a dispatch. What are the remaining issues you need to debug?

Note that we wouldn't want to follow the dispatch flow. We just want it to be an external function call with the number of threads as params. We need to do a research how we encode parallelism. Until then, just an external function would be sufficient.

If the ukernel flow enforces using the dispatch with workgroup configuration, we might need to find a different way. Thanks!

**Comment by ramiro050** [comment]
The full gist is here: https://gist.github.com/ramiro050/c7a847d63fd4187b258fb2bcddb80b62

This is what things look like before lowering to LLVM:

```mlir
// -----// IR Dump After LowerUKernelOpsToCalls (iree-codegen-lower-ukernel-ops-to-calls) //----- //
module {
  func.func private @xnnpack.mul2_workgroup(memref<f32>, index, index, memref<f32>, index, index, memref<f32>, index, index, index) attributes {llvm.bareptr = true}
  func.func @xnnpack.mul2_dispatch_0() {
    %c32_i64 = arith.constant 32 : i64
    %c0 = arith.constant 0 : index
    %0 = hal.interface.constant.load[0] : i32
    %1 = hal.interface.constant.load[1] : i32
    %2 = hal.interface.constant.load[2] : i32
    %3 = hal.interface.constant.load[3] : i32
    %4 = arith.extui %0 : i32 to i64
    %5 = arith.extui %1 : i32 to i64
    %6 = arith.shli %5, %c32_i64 : i64
    %7 = arith.ori %4, %6 : i64
    %8 = arith.index_castui %7 : i64 to index
    %9 = arith.extui %2 : i32 to i64
    %10 = arith.extui %3 : i32 to i64
    %11 = arith.shli %10, %c32_i64 : i64
    %12 = arith.ori %9, %11 : i64
    %13 = arith.index_castui %12 : i64 to index
    %14 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<?xf32>{%13}
    memref.assume_alignment %14, 64 : memref<?xf32>
    %15 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : memref<?xf32>{%8}
    memref.assume_alignment %15, 64 : memref<?xf32>
    %16 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : memref<?xf32>{%13}
    memref.assume_alignment %16, 64 : memref<?xf32>
    %base_buffer, %offset, %sizes, %strides = memref.extract_strided_metadata %14 : memref<?xf32> -> memref<f32>, index, index, index
    %base_buffer_0, %offset_1, %sizes_2, %strides_3 = memref.extract_strided_metadata %15 : memref<?xf32> -> memref<f32>, index, index, index
    %base_buffer_4, %offset_5, %sizes_6, %strides_7 = memref.extract_strided_metadata %16 : memref<?xf32> -> memref<f32>, index, index, index
    call @xnnpack.mul2_workgroup(%base_buffer, %offset, %strides, %base_buffer_0, %offset_1, %strides_3, %base_buffer_4, %offset_5, %strides_7, %13) : (memref<f32>, index, index, memref<f32>, index, index, memref<f32>, index, index, index) -> ()
    return
  }
}
```

I might be misunderstanding things, but this seems to be what we want. The op turns into a single call to an external function.

**Comment by okkwon** [comment]
Nice! LGTM.

Nit: One thing to consider is the naming. We may swap `<opname>` and `<opname>_workgroup` so that the generated mlir side has `_workgroup` while we have the generic op name in the op implementation side. We may use `_wrapper` if `_workgroup` does not deliver the meaning clearly. More examples: `_workgroup_wrapper` or `_wg_wrapper`.

**Review by okkwon — APPROVED** [review]
Looks great. The input is so simple. :-)

**Pull request merged**
